<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Promise的API：excutor 和 then、catch</title>
</head>

<body>
    <script>
        // excutor 函数 ((resolve, reject) => {})
        let p = new Promise((resolve, reject) => {
            // 同步调用的
            console.log(111);
            // resolve('success');
            // reject('faild');
            throw 2
        })

        // then(参数1，参数2)
        // 参数1 和 参数2 都是函数类型
        // 参数1： resolve()：成功的回调函数
        // 参数2： reject()：失败的回调函数
        // 参数2可以不写，只写一个参数时为成功的回调函数。
        p.then((value) => {
            console.log(value); // success
            throw value;
        }, (reason) => {
            console.log(reason);    //faild
            throw reason;
        })
        console.log(p);

        // 如果then 方法中不设置返回值，then方法返回结果为一个成功的promise，返回值为 undefined
        // 如果有返回值 ，类型为 非promise 时，then方法返回一个成功的promise，返回值为 输出的返回值。
        // 如果有返回值且为promise类型，则根据返回的promise来决定返回的promise的状态和结果。
        // 如果then中抛出异常，则根据当前的状态返回一个promise对象，返回值为抛出的值

        // reject() 错误的回调函数
        p.catch((reason) => {
            console.log(reason);    //faild
        })


    </script>
</body>

</html>